### ISSUE TITLE
Payments Not Received

### ISSUE THREAD

**Issue by sm18038589** [Nelbert442/dero-golang-pool#8]
Hi

I've done a little pool mining with you using my Dero Web Wallet address and also my TradeOgre Dero address. In both cases I have not received any of my payments in spite of them showing up in your dashboard history. Please help. I can provide further details here or by email (preferred). Let me know.

Thanks
S

**Comment by Nelbert442** [comment]
Feel free to send me a DM on discord @Nelbert442 (https://discord.gg/H95TJDp), otherwise we can resolve in other manners if you would prefer not use discord , just let me know.

**Comment by Nelbert442** [comment]
Noticed you may have not hit the recaptcha for discord server. Feel free to mail me at Nelbert442 at protonmail.com , can get it figured out.

Another point of reference for the web wallet, ensure it's fully synced / tried to resync balance (instead of 0 try something like  7215000 , depending on when tx was): https://docs.dero.io/rtd_pages/basic_webwallet.html#rescan-blockchain

**Comment by Nelbert442** [comment]
In discussion via email in effort to resolve the issues. Sent proof of sending via each referenced TX. Seems to be a wallet sync issue as well as potentially a too small amount to TradeOgre or other, will continue working on resolution. 

At this time this isn't an issue with the pool code itself and will continue troubleshooting off this medium. Of course, OP feel free to reopen this or a new one if you feel otherwise. Will close this one out. Thanks.
