### ISSUE TITLE
Website no stats update

### ISSUE THREAD

**Issue by oxzhor** [Nelbert442/dero-golang-pool#9]
Hi

I install the software and setup an wallet and the deamon and run both in an screen. Then I start the frontend and the website showup. But if I connect with xmrig the website not show any stats what is wrong?

Thank you.

**Comment by Nelbert442** [comment]
Please see: https://github.com/Nelbert442/dero-golang-pool/issues/4

Ensure your js files are pointing to the configured API settings within config.json. see https://github.com/Nelbert442/dero-golang-pool#host-the-frontend and https://github.com/Nelbert442/dero-golang-pool#host-the-api

**Comment by oxzhor** [comment]
Nice that did the trick. Only the Network: 165.00 MH/sec Difficulty: 4,455,070,223 Height: 930,704 are wrong need this to sync still?
Thank you.

**Comment by Nelbert442** [comment]
Yeah you'll need to be fully synced before mining to the daemon. You can always modify your upstream (daemons) to include explorer.dero.io:20206 in the meantime or so. Otherwise can download a snapshot of the chain at https://blockchain.dero.network to speed it up too if you want, at least give it a head start.

Full sync from 0 on a decent machine/network (SSD basically a requirement) will take somewhere in the week or so range. So the snapshot helps a lot. Bootstrapping will be more avail once Stargate goes live, but for now need to ensure sync.

**Comment by Nelbert442** [comment]
Closing out issue - discussion/question regarding stats and frontend populating was solved via API reference documentation. Addtl details provided related to daemon syncing
